language: elixir
elixir:
- 1.10.3
otp_release:
- '23.0'
service:
- postgresql
before_script:
- cp config/travis.exs config/test.exs
- MIX_ENV=test mix do ecto.setup
script:
- MIX_ENV=test mix do deps.get, ecto.migrate, test
deploy:
  provider: heroku
  api_key:
    secure: jjJgpTak6eJUddeDl6Oc7agrSJ3AITod/koFijWL1z8vRTnb5GzspBJjEtwZGHUAQBUBqpDFAJ+/Bht8RUAXjRyU7k7nUvUV9J+CM3MMssQsgUmMrx4ToxNQr35+9ZEb76xNtpRVmqNKdkS362GBW3g7n3g+JGKB7XsliAb+F61I5EIuljQ8InL18+adx4tWsmqVjxEGXT2ie7v/WQyXmQO3JMCJjs2EskubWmc7v1VlJkfuA4KMkcRmfUQZPkJmFFyBUcrxO+Cjrf2bpPbominJjwO6KL5hQo/UibbJriHlsLyYdXrzIkaoCVQ4s+OITSOUKEaiEpcXbNqRExEZl8FpAsnfKXq5q7A+qeAGYADMrU6Bj5vUfw75aEzvTD5g2QPPRTluF2bsKtz7hbQ5l0wfLCIf3VXXbMj6Iucp8VVcDLdXvjhjGDdgDvXn+oujyuPEANEG8Qes+4U4MpQUCjcohG/HL7Xb5nfcCx9GM30+szNjw1K9rioiq5gz68egqeljJ/VfA7UeDvm65Cd0llBp4BzTuyzPhHStuVIhrLRb2pWA6j22zO/pyLIUkCw9VcY4RolzornZjW0Y+wB1W4WZl0S0t6bC/x5HIbut9GNbFD9R+yzx4J4zqGNiG+WdagO/kl3ftCvbu1G9mvzVthbuyb21VKRTtK8vbACcIlU=
  app: shielded-eyrie-94049
  on:
    repo: vtomogz/debtmanager
  skip_cleanup: 'true'
after_deploy:
- heroku run mix ecto.migrate -a shielded-eyrie-94049
