language: elixir
elixir:
  - '1.10.3'
otp_release:
  - '23.0'
addons:
  postgresql: '11.7'
service:
  - postgresql
before_script:
  - cp config/travis.exs config/test.exs
  - MIX_ENV=test
script:
  - MIX_ENV=test mix deps.get --only test
  - MIX_ENV=test mix ecto.setup
  - MIX_ENV=test mix ecto.migrate
  - MIX_ENV=test mix test
