language: elixir
elixir:
  - '1.10.3'
otp_release:
  - '23.0'
addons:
  postgresql: '11.7'
before_script:
  - cp config/travis.exs config/test.exs
  - mix deps.get
  - mix deps.compile
  - mix ecto.setup
