language: elixir
elixir:
- 1.10.3
otp_release:
- '23.0'
service:
- postgresql
before_script:
- cp config/travis.exs config/test.exs
- MIX_ENV=test mix do ecto.setup
script:
- MIX_ENV=test mix do deps.get, ecto.migrate, test
deploy:
  provider: heroku
  api_key:
    secure: NqqAv0AeQDpR4slgbYi8FdgHlvJt7phplXJfaoqRncyQ75ay+PJ1WRd5TmbJVDd5ooqlKRNy16RItyTvO6HKvdYE+/2Bh5NRX1Hc3EoAk5h6fc5zGhOPrBJcJ7qXigla2Gc3oLIaO7g2Hgi+urENVWuEFa2YuaLwn0esYbMAuf0fcgHF/YRzN9Qzm0VkhFPI1NomvDrAGedII31qynLYLM/wmkA6BaLQRnyEuxtbx94M61508fGl/A3Sq8jhiZxCrRBM6Slt+hFWWsJFXw2U72gT4IQw+fRcEHV7OhKHbmaOXaSLKtNTSOVaYNNDI0IQfM0BKaBRaE8iPAHjA6hHI3h0W3Db9YClL7jIvkBvFioY96WS8X2FbjhUOhlGmGkqEn0AMihyfsyJHE48Ys9IEFRpOeNxdnx5kYEoI3HqnaWqDo3YQ8B7Sz++Pp8dRCDEOX/cxnWCR5OZdKv9Utgfc7O4g4AEay5rgzJNXZyDZSrfqR5xwf+kLY9Yzo0kZeepEzjBO8orA09WeeFom3DTZFavl5Dq6mkaa+TQwremrivmooJaVPF47oFCZhSBkfOUD4tl1EMU4vQZVoAkGAJJIWm3Eays7jymluDvd0Vek8AbY7/kCB0KxjtglqYt+PApjZqQqovmv1C/3Yi5peGpYGjA9dLMY9OwiDC7mIJVWUE=
  app: shielded-eyrie-94049
  on:
    repo: vtomogz/debtmanager
  skip_cleanup: 'true'
after_deploy:
- heroku run mix ecto.migrate -a shielded-eyrie-94049
