language: elixir
elixir:
- 1.10.3
otp_release:
- '23.0'
service:
- postgresql
before_script:
- cp config/travis.exs config/test.exs
- MIX_ENV=test mix do ecto.setup
script:
- MIX_ENV=test mix do deps.get, ecto.migrate, test
deploy:
  provider: heroku
  api_key:
    secure: x/wKZC89WaPfQsEUmW+GrwK00ypcF6a9BQoGARh4SUF8j0GVCqJvoiL94ThCYCjLYJJuRYmEdqmABEaegH7alTzzn1h05tvfbllYPSDMKqx5cjd43livK13ctDcEi73nnvxUEIcclR57PKvNYG8k63f97VDbBjHKqpb7DFtDFAoUsl0MZkptl+EtvLaGFJ/Pj8Yi64Rxm813hkVLR+jZIkFi3Kp7LDERxA4wWSt9AlaqxIi12L8MG8VRTZcl87RSfmud7iBNkTSj6+YA5n0wpdo5Dba/fjm6KYjFT4u0tJr1o6DLYnHQvxxti/QEtP2CD7CpSEv2Bd+NrRtUi4kycXTXrJI81N7pASlUbf8nbEea0lOAV/FLo2Ny/4V5FbVwQN9L51oTMZZJBlHTholdwrXDWws0+9EbgV4HZujtuIEx7ZJFi1EvrPUWU8of0fgIoGgoVqhs8K88cl5BAQs04WnagWMU/lgZYQqunn1o2gyDqqImAC2FunTI8DY5pUW/atvAornn/0ZYreK5ZrFP5QC7vKQ4D8wr6EfoBj3iQO2k1LuIA1wTQlOV3d7Lzpr89zHmChVOcwOnM5VefUTbFixF5H5pGiYfQmYMZIUNyJTkNGMTywv80ejpyGnEMpMO8U1ATGrFf2GsqEf4K/jkJwj4A2HPrF5O48zLORRz3Cc=
  app: shielded-eyrie-94049
  on:
    repo: vtomogz/debtmanager
  skip_cleanup: 'true'
after_deploy:
- heroku run mix ecto.migrate -a shielded-eyrie-94049
