deploy:
  provider: heroku
  api_key:
    secure: jDAlJw5PlTVsgzp+WtS7aogYURzHTXMMXeKMM0beXYSDLMQL3xnbdBTA++uSlDWflyL+V6xHybfRsN18SGw0JzoaUiS5RdxIvbyxYzVDE4Q5a9ekhUNH1XerT3z3WhRcXgnB7+PS5W33XqV00yrwLmQz56fOwYtsxY83IqoAWekWGNSjhpQLayenp4PR9oStM2d1MwQRrcSfnG21zJ3z3gsVBYQunkrrCTt7I1dj2bS88k80c1WYL2VIVYFmjr2hdtX2LwjAhMMYoCFQ8O+xIZ7FtIByfTlfBI9iQ6kdXjDJnKjio79vSmXs46zcI89bNGFb5uLoEQ8c4UWsbpU4JSHqjT4YKz6OOwXBjf7pR9l+oW398ZxyIsjnq/YCLKBAHIr3cENEBMZV0Cynb/l3l8xte/mo3fivJhOs0C3WMam9zm2Tzxd4LyBSIC8MFTR4hKUpFndBQGculTtD6enpMpzE2bCrytQLY3exXs645cIxIeSY9CQcuVZOTBuqW1Z7LhD41iMfl1BR1s7HFKBw6ywzbWYNt6L5ywj/aMd2kAY4kjhvLwEXjSbJOdBSyNcUyO3tMlcHvnkwoq+bO/hi4F4YEXT9lPPEC/lZI7brETAOoC36eKzx82kQHdU9h2yJEIVslUrLe9ncP+C8YkWfor1fJjN8qVvP+GBGw+R0cCY=
  app: shielded-eyrie-94049
  on:
    repo: vtomogz/debtmanager
  skip_cleanup: 'true'
