language: elixir
elixir:
  - '1.10.3'
otp_release:
  - '23.0'
addons:
  postgresql: '11.7'
service:
  - postgresql
before_script:
  - cp config/travis.exs config/test.exs
script:
  - mix deps.get --only test
  - mix ecto.create
  - mix ecto.migrate
  - mix test
