language: elixir
elixir:
- 1.10.3
otp_release:
- '23.0'
service:
- postgresql
before_script:
- cp config/travis.exs config/test.exs
- MIX_ENV=test mix do ecto.setup
script:
- MIX_ENV=test mix do deps.get, ecto.migrate, test
deploy:
  provider: heroku
  api_key:
    secure: eGCRX1M7GHorEvbIxQAZvNMYZR047XoOxZcfwIJ4EeEes4dvzXFh5op/yIHgwos6dIAQqfYCm5TmI4pwEg5z0Uthz+JX49r3xJ7j1w6HT9S8cIi6o7o6pmO2VVXO9r2q6sRTB+CKbl3ZiR+J/mfQRxyZipzhI5NmfTE+X5EHsqgRzyymsRccc8kII/bqvy7dyWanDNJqwKxnT4bgzcxtIhNFVKAe5iH4uwgVhWpYxbn4Xb6WXR0uQiYzzzRLGyTEQJ0Q2emTED7jn269n3Eo2DHqM4RuPib8CmWWw3pgDOgFjJaBxy2hhPDHqjJDvNUftAWGaHrRaydR4dcYsIdMYhkd1yvMqkIPfMrgQBu+uo78/mAdstdR7tB1ATi+U9YSmxE30/I5ZxnlSiu3GjwxgBKyO99IAIuB5lc21D1ZjNwoMEB+wQR5Rr4kRuJJkRPVZmUL0j/ZAOnBwcpyMxj8Spw3KtyXYMQl2GqqIDbsuJ/WQ8Qiz+uNtVjImCDxXgu04AfFQPA2iRSX6QI/U215mkURPtlvuBqg18pWWfvCCvr6dN3uRHZcCfhh7N/gk33a2+zSxIXm7R/xyPSGdC41v0ZZqHM3Vxh3ccwvJNWNogVm23bjoTZK8lSgwgFDx3mwzov/Li+VkSlCG9u7Joyg3ySZrCDJm6RG07rfpcasJbM=
  app: shielded-eyrie-94049
  on:
    repo: vtomogz/debtmanager
  skip_cleanup: 'true'
after_deploy:
- heroku run mix ecto.migrate -a shielded-eyrie-94049
